### ISSUE TITLE
inplementation on KuaiRec

### ISSUE THREAD

**Issue by Jiaju-Chen** [BgmLover/iDCF#1]
Nice work and great ideas! As far as I know, Kuairec is another unbiased dataset with a fully-exposure test dataset. 

I find it hard to tune iDCF on KuaiRec. Have you tested this dataset before? Can you give me some tips to tune the data on Kuairec (such as the optimal hyperparameter of KuaiRand)? 

Thanks a lot for your help!

**Comment by BgmLover** [comment]
Hi Jiaju,
Sure I have tested the dataset. The optimal hyperparameter is recorded in the code. e.g., see iDCF.py line 156 -- 158.
If you have any further question, feel free to email me via qzhangbo@connect.ust.hk :)
